# Generated by Django 5.1 on 2024-09-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='file_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='files',
            field=models.ManyToManyField(blank=True, to='task.file'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
