# Generated by Django 5.1 on 2024-09-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_messages_file_id_messages_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='unknown', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
